export const DataComment = [

    {
        id: 1,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 2,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 3,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 4,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 5,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 6,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 7,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 8,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },
    {
        id: 9,
        com_name: "Дима Середин",
        com_desc: "Текст тестового отзыва, предлагаю на главную страницу рендомно выводить только отзывы с оценкой от 4.5 и выше…",
        com_job: "SMM-менеджмент",
        com_rating: 4.5,
        start: "<i class='bx bxs-star star' ></i>",
        com_ava: "./images/a1.png",
    },



]